default:
	g++ -O3 -Wall -Wextra -lsfml-graphics -lsfml-window -lsfml-system -I/usr/include/bullet -lBulletCollision -lBulletDynamics src/*.cpp -opolymorphosis.bin

debug:
	g++ -g -pg -lprofiler -Wall -Wextra -lsfml-graphics -lsfml-window -lsfml-system -I/usr/include/bullet -lBulletCollision -lBulletDynamics src/*.cpp -opolymorphosis.bin
