default:
	g++ -O3 -Wall -Wextra -Werror -Wno-unused-parameter -std=c++0x -lsfml-graphics -lsfml-window -lsfml-system -I/usr/include/bullet -lBulletCollision -lBulletDynamics src/*.cpp -opolymorphosis.bin

debug:
	g++ -g -Wall -Wextra -Werror -Wno-unused-parameter -std=c++0x -lsfml-graphics -lsfml-window -lsfml-system -I/usr/include/bullet -lBulletCollision -lBulletDynamics src/*.cpp -opolymorphosis.bin
