library global;

var stage;
var canvas;
var view;
var random;
var debugText;
var debugShape;
var amountOfRain;
var resourceManager;
var gameText;
var background;
bool debug = true;
bool relaxMode = false;
bool canDie = false;
bool isDead = false;
bool colorLeaves = true;
String mode;
String debugMessage;
var treeBase, rootBase;
