library global;

var stage;
var canvas;
var view;
var random;
var debugText;
var debugShape;
var amountOfRain;
var resourceManager;
var gameText;
var background;
var eyeToggle;
var frameTime;
bool debug = false;
bool relaxMode = false;
int branchesToDie = 5;
bool isDead = false;
bool colorLeaves = false;
String mode;
String debugMessage;
var treeBase, rootBase;
